import waifulist as w

waifu = (w.texas1,
         w.texas2,
         w.texas3,
         w.texas4,
         w.texas5,
         w.texas6,
         w.texas7,
         w.texas8,
         w.exu1,
         w.hoshiguma1,
         w.hoshiguma2,
         w.hoshiguma3,
         w.hoshiguma4,
         w.dobermann1,
         w.dobermann2,
         w.dobermann3,
         w.dobermann4,
         w.gravel1,
         w.gravel2,
         w.shirayuki1,
         w.shirayuki2,
         w.shirayuki3,
         w.shirayuki4,
         w.shirayuki5,
         w.shirayuki6,
         w.orchid1,
         w.melantha1,
         w.mousse1,
         w.popukar1,
         w.popukar2,
         w.popukar3,
         w.catapult1,
         )
